# Generated by Django 4.2.7 on 2024-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='id_tournament',
            field=models.IntegerField(default=0),
        ),
    ]
