# Generated by Django 4.2.7 on 2025-02-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_tournament_id_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
