# Generated by Django 4.2.7 on 2025-01-16 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ping_pong", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_as_winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
