# Generated by Django 4.2.7 on 2025-03-20 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="defaults/user.jpg",
                        null=True,
                        upload_to="user_photos",
                    ),
                ),
                ("external_photo_url", models.URLField(blank=True, null=True)),
                ("online_status", models.BooleanField(default=False)),
                ("language", models.CharField(default="", max_length=10)),
                ("two_fa", models.BooleanField(default=False)),
                ("totp_secret", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True, related_name="friend_of", to="user_profile.profile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
