# Generated by Django 4.2.7 on 2025-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="external_photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="defaults/user.jpg",
                null=True,
                upload_to="user_photos",
            ),
        ),
    ]
