from django.contrib.auth.models import User
user1 = User.objects.create_user(username='dins', password='1234')
user2 = User.objects.create_user(username='bobby', password='1234')
user3 = User.objects.create_user(username='nuria', password='1234')
user4 = User.objects.create_user(username='julia', password='1234')
user5 = User.objects.create_user(username='diana', password='1234')
user1.save()
user2.save()
user3.save()
user4.save()
user5.save()
